services:
  - type: web
    name: zapjud-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: "0"
    plan: free
